version: '3.8'
services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas